### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by blockspacer** [blockspacer/CXXCTP#55]
add CI/CD

**Comment by jatin69** [comment]
@blockspacer I'd be happy to take this on. Github Actions will do the job.
Can you please elaborate on what do you need in the CI and CD?
For eg, first make, then test, etc, etc. What exactly is the flow needed?

**Comment by blockspacer** [comment]
@jatin69 
Is it possible to add automated tests (Catch2/Gtest), but only for `master` branch?
I`m thinking about something like http://gueepo.me/blog/simple-ci-for-cpp/

Note that project uses heavy deps: clang and cling, but both are optional.

**Comment by jatin69** [comment]
@blockspacer
Yes it's possible to only add it for master branch. Although i'd also recommend adding them for PRs. 
Dependencies are not a problem. 

The article you provided uses circleCI. It's very well known and good. However it's third party. GitHub recently introduced inhouse CI. So i was thinking to integrate github actions instead of circleCI. 

Let me know if you want me to go for it. Also the compile steps, commands, and their order will help me write them down.

**Comment by blockspacer** [comment]
@jatin69 
It is good idea to add them for PRs.

Any help with CI/CD is appreciated.

Github actions are awesome.

May current [Dockerfile](https://github.com/blockspacer/CXXCTP/blob/master/Dockerfile) be used with Github actions or it is better idea to create separate Dockerfile for CI/CD?

Note that tests folder in-dev now, but tests structure will not change much (just new tests will be added).

**Comment by jatin69** [comment]
@blockspacer
Alright i'll take this on. Will have to see about that Dockerfile. I'll let you know if I have more questions. Thanks.

**Comment by jatin69** [comment]
@blockspacer 
Hey, I went through the readme 5-6 times. There are a lot of alternatives in the readme. I can't figure out the bare minimum to build and test the project. 
If you can spare some time, I'll appreciate a bare minimum list of commands and dependencies you want me to add to CI, so it'll just build and test the system.
